[package]
name = "yathzee-world"
version = "0.0.1"
edition = "2024"

[dependencies]
actix-files = "0.6.6"
actix-web = "4"
env_logger = "0.11.8"
log = "0.4.27"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio"] }
